version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

# Build documentation using Sphinx
sphinx:
  configuration: docs/source/conf.py
  builder: html

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt
